### PR TITLE
Enable SSL in haproxy.cfg if patroni_restapi_certfile is defined

### PR DESCRIPTION
**Pull request by danopt**
https://github.com/kostiantyn-nemchenko/ansible-role-patroni/issues/101

### CODE REVIEW

**Comment by danopt** [comment]
Tested with both configurations.

- No SSL:
haproxy-no-ssl
- SSL:
haproxy-ssl

**Review by widhalmt — CHANGES_REQUESTED** [review]
What are you checking for?

If you want add the string when `patroni_restapi_certfile` is set to `true` then use `| bool`. If you're checking if the variable is defined at all please use `is defined`.

**Comment by danopt** [comment]
@widhalmt Thx. I want to check if the variable is defined at all. Currently, the variable is defined with `patroni_restapi_certfile: ""` in the defaults/main.yml or does it mean undefined?

I guess I'll take a look at it.

**Comment by danopt** [comment]
Hi @widhalmt,

we need to check if the variable is defined, but assigned to an empty string "" (?) :-)

I'm used to using only `if` because of Python. Small example:
```
>>> no_ssl = ""
>>> if no_ssl:
...   print('pass')
... else:
...   print('fail')
... 
fail
>>> ssl = "somestring"
>>> if ssl:
...   print('pass')
... else:
...   print('fail')
... 
pass
```

**Edit**
When I would use `if no_ssl != ""` pylint gives a warning that I should use `if` only for that condition.

I also tested it with Jinja. I assigned two variables in the playbook:
```
    test_no_ssl: ''
    test_ssl: 'somestring'
```

test.j2:
```
{% if test_no_ssl is defined %}
    test_no_ssl - is defined - pass
{% else %}
    test_no_ssl - is defined - fail
{% endif %}
{% if test_no_ssl %}
    test_no_ssl - if - pass
{% else %}
    test_no_ssl - if - fail
{% endif %}
{% if test_ssl %}
    test_ssl - if - pass
{% else %}
    test_ssl -if - fail
{% endif %}
```

Output:
```
    test_no_ssl - is defined - pass

    test_no_ssl - if - fail

    test_ssl - if - pass
```

That is exactly what I need. Is it wrong to use only `if`?

**Comment by widhalmt** [comment]
Only `if` can be misleading.

Why not remove the definition in `defaults` and us `{% if variable is defined %}`. That's more or less the ususal way to do it.

About the `""` empty string... personally I would be ok with the playbook just failing when it's set to an empty string because that doesn't make any sense - at least to me.

So I see these options with their respective outcome
* Variable is not defined: skip that string in the template
* Variable is set to something that doesn't work like `""`: Just let the tasks run and fail
* Variable is set to something useful: Works as expected

If you see that differently, I'll happily let myself get convinced.

**Comment by danopt** [comment]
@widhalmt You're right, it's hard to read, and also, in this way, I can see which role variables are really required or optional. 

So I commented all unnecessary variables of the REST API of Patroni and changed the condition.

**Review by widhalmt — APPROVED** [review]
Looks good to me as far as I can tell.

**Pull request merged**
