### PR TITLE
Add prototype of Molecule tests

### PR DESCRIPTION
**Pull request by widhalmt**
Hi,

You asked for Molecule tests for this role. Here's a quick hack as a prototype. I hope that works.

Feel free to change anything or ask if you need some insight.

Cheers,
Thomas

### CODE REVIEW

**Comment by danopt** [comment]
Debugged `journalctl -xe`:
```
"-- Unit patroni-watchdog.service has begun starting up.",
"Oct 27 14:22:56 instance modprobe[2610]: /sbin/modprobe: error while loading shared libraries: libzstd.so.1: cannot open shared object file: No such file or directory",
"Oct 27 14:22:56 instance systemd[1]: patroni-watchdog.service: main process exited, code=exited, status=127/n/a",
"Oct 27 14:22:56 instance systemd[1]: Failed to start Makes kernel watchdog device available for Patroni.",
"-- Subject: Unit patroni-watchdog.service has failed",
```

**Comment by widhalmt** [comment]
Hm, could it be that Patroni uses Kernel features that won't let it run in Docker? Otherwise, maybe the Containers are just missing some basic packages that are not covered by dependencies or the Patroni role.

**Comment by danopt** [comment]
Success.

Required packages: 
  - libzstd-devel
  - openssl11-libs

Required volumes:
      - /sbin/modprobe:/sbin/modprobe
      - /lib/modules:/lib/modules

watchdog and Patroni are starting, which means there is no configuration error in the syntax of Patroni and watchdog. That should be ok for basic testing for this role.

**Comment by danopt** [comment]
>  Otherwise, maybe the Containers are just missing some basic packages that are not covered by dependencies or the Patroni role.

@widhalmt Yes, you were right. Didn't read your message while I was coding, but it was missing volumes and packages. :-)

**Comment by DanOPT** [comment]
@widhalmt should we add Ubuntu 16.04, else I would mark this PR as "Ready for review"

**Review by widhalmt — COMMENTED** [review]
As far as I can tell, it looks good to me. But I can't approve my own pull request, even when you changed it afterwards. :-)

**Review by danopt — APPROVED** [review]

**Review by afeefghannam89 — APPROVED** [review]

**Pull request merged**
